[tool.poetry]
name = "validio-plotting"
version = "0.1.0"
description = "App to graph  metrics from Validio SDK"
authors = ["Validio <support@validio.io>"]
license = "Apache-2.0"
packages = [{include = "validio_plotting"}]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
validio-sdk = "^0.13.1"
typer = "^0.7.0"
prompt-toolkit = "^3.0.43"
validio-cli = "^0.13.1"
plotext = "^5.2.8"


[tool.poetry.group.dev.dependencies]
ruff = "^0.1.11"
pytest = "^7.4.4"
black = "^23.12.1"
mypy = "^1.8.0"
licensecheck = "^2023.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
validio-plotting = "validio_plotting.main:main"

[tool.ruff]
fix = true

select = [
    "ARG", # flake8-unused-argument
    "C4",  # flake8-comprehension
    "D",   # pydocstyle
    "E",   # pycodestyle error
    "F",   # pyflakes
    "I",   # isort
    "N",   # pep8-naming
    "PIE", # flake8-pie
    "PL",  # pylint
    "PT",  # flake8-pytest-style
    "PTH", # flake8-use-pathlib
    "RET", # flake8-ret
    "RUF", # ruff specific rules
    "SIM", # flake8-simplify
    "UP",  # pyupgrade
    "W",   # pycodestyle warning
]

ignore = [
    "D203",    # `one-blank-line-before-class` Incompatible with D211
    "D212",    # `multi-line-summary-first-line` Incompatible with D213
    "D205",    #  blank line required between summary line and description
    "PLR0913", # Too many arguments to function call (named arguments take care of this)
]

[tool.ruff.per-file-ignores]
"__init__.py" = [
    # We don't need docstrings in __init__
    "D104",
]

"*/tests/*.py" = ["D"]

[tool.ruff.pydocstyle]
convention = "google"

[tool.black]
preview = true

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = false
plugins = "pydantic.mypy"
